### ISSUE TITLE
RoadNetwork RoadMap

### ISSUE THREAD

**Issue by sairam4123** [sairam4123/Godot-Road-Builder-3D#5]
Hello everyone, we have a road map for RoadSystem too!

- [x] Basic Road Network with graph.
- [x] Road Tool for RoadSegmentLinear (partially done, Snapping has not yet been ported.)
- [x] Road Tool for RoadSegmentBezier
- [x] Road Renderer for Segments
- [x] Road Renderer for Intersections
- [ ] Road Tool with states for each type of segment.
  - [ ] RoadToolFreeform - pending
  - [x] RoadToolStraight
  - [x] RoadToolCurved
- [x] Multi-edged graph support. (No self-loops)
- [x] Rewritten Road Network with new API
- [x] Road Intersection Node
- [x] Road Managers for RoadNetworkInfo and RoadSegmentTypes
- [ ] Road Markings
- [ ] Road Saving and Loading
- [ ] Road Network Info editor.

We'll be implementing all these into the game.

We also plan to make a integration for the editor so it's you can use it as a Addon.

**Comment by sup-Udh** [comment]
ok nice.

**Comment by Naman-Biswajit** [comment]
👍
